import os
from dotenv import load_dotenv

load_dotenv()

GEMINI_QGEN_API_KEY = os.getenv("GEMINI_QGEN_API_KEY")
GEMINI_FEEDBACK_SCORES_API_KEY = os.getenv("GEMINI_FEEDBACK_SCORES_API_KEY")
GEMINI_FEEDBACK_SUMMARY_API_KEY = os.getenv("GEMINI_FEEDBACK_SUMMARY_API_KEY")
GEMINI_FEEDBACK_FLAGS_API_KEY = os.getenv("GEMINI_FEEDBACK_FLAGS_API_KEY")

GEMINI_QGEN_MODEL = "gemini-2.5-flash"
GEMINI_FEEDBACK_MODEL = "gemini-2.5-flash-lite"

ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY")
